// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
:projectid: rest-client-reactjs
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-description: Explore how to access a simple RESTful web service and consume its resources with ReactJS in Open Liberty.
// :page-releasedate: ...
:page-related-guides: ['rest-intro', 'rest-client-java']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Consuming a RESTful Java web service with ReactJS
:page-seo-description: A getting started tutorial with examples on how to access a RESTful Java micoservice and deserialize the returned JSON in ReactJS.
:guide-author: Open Liberty
= Consuming a RESTful web service with ReactJS

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to access a simple RESTful web service and consume its resources with ReactJS in Open
Liberty.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn 

You will learn how to access a REST service and deserialize the returned JSON that contains a list of artists, their albums and other ambiguous artist features by using an HTTP client with the ReactJS library. You will then present this data using a ReactJS element in the form of a paginated table.

https://reactjs.org/[ReactJS^] is a JavaScript library used to build user interfaces. Its main purpose is to incorporate a component-based approach to create reusable UI elements. React also allows you to interface with other libraries and frameworks. Note, the names ReactJS and React are used interchangeably. To learn more about React, visit: https://reactjs.org/[React].

The React application in this guide was created and configured for you in the `frontend` directory. The application uses the https://reactjs.org/docs/create-a-new-react-app.html[Create React App] prebuilt configuration to design the modern single-page React application. `Create React App` is a comfortable environment for learning React, and is the best way to start building a new single-page application in React. To learn more about this environment setup, see https://github.com/facebook/create-react-app[create-react-app] GitHub repository. 

artists.json
[source, json, linenums, role="code_column"]
----
include::finish/src/resources/artists.json[]
----

The REST service that provides the resources was written for you in advance and responds with the [hotspot]`artists.json` in `src/resources`.

To learn more about REST services and how you can write them, see
https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service^].

// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Try what you'll build
// =================================================================================================

[role='command']
include::{common-includes}/twyb-intro.adoc[]

Navigate your browser to the application root http://localhost:9080/artists[http://localhost:9080^] to
see the following output:

[subs="quotes", role="no_copy"]
----
[{"id":"1","name":"foo","followers":"12313K","genres":"pop","albums":[{"title":"album_one","artist":"foo","ntracks":12},{"title":"album_two","artist":"foo","ntracks":15}]},{"id":"2","name":"bar","followers":"12313K","genres":"hip hop","albums":[{"title":"foo walks into a bar","artist":"bar","ntracks":12}]},{"id":"3","name":"dj","followers":"12313K","genres":"rock","albums":[]}]
----

// =================================================================================================
// Starting the service
// =================================================================================================

== Starting the service

Before you begin the implementation, start the provided REST service so that
the artist JSON is available to you.

Navigate to the `start` directory to begin.

First, you need to build the frontend by running the Maven `generate-resources` goal:
[role='command']
----
mvn generate-resources
----

Note that you can rebuild the frontend at any time with the Maven `generate-resources` goal.
Any local changes to your JavaScript are picked up when you build the
frontend. These changes are also automatically rendered to your webpage template.

[role='command']
include::{common-includes}/devmode-start.adoc[]

You can find your artist JSON at the
http://localhost:9080/artists[http://localhost:9080/artists^] URL.

// =================================================================================================
// Creating the React component
// =================================================================================================

== Creating the React component

In React, a component does a specific functionality, where a web application in React is 
simply a collection of components. You will create the component that is used in the application to acquire and display data from the REST API. 

Fetchdata.js
[source, javascript, linenums, role='code_column hide_tags=axios-library,react-table,get-posts,mount-posts,render-posts']
----
include::finish/src/main/frontend/src/Components/Fetchdata.js[]
----

App.js
[source, javascript, linenums, role='code_column']
----
include::finish/src/main/frontend/src/App.js[]
----

index.js
[source, javascript, linenums, role='code_column']
----
include::finish/src/main/frontend/src/index.js[]
----

server.xml
[source, xml, linenums, role='code_column']
----
include::finish/src/main/liberty/config/server.xml[]
----

The [hotspot=react-library file=0]`React library` imports the default export from the react package, and the component named export from the package. An inheritance to the React Component is created to write the [hotspot=class file=0]`Fetchdata` component. 

[role="code_command hotspot file=0", subs="quotes"]
----
#Update the `Fetchdata.js` file.#
`src/main/frontend/src/Components/Fetchdata.js`
----
[role="edit_command_text"]
Add the object to represent the [hotspot=state-object file=0]`state` of the posts that will appear on the paginated table. 

The `Fetchdata` component also needs to be [hotspot=export-fetchdata file=0]`exported` as a reusable UI element that can be used across your application, such as in the [hotspot=import-Fetchdata file=1]`App.js` file. The `App.js` file returns the `Fetchdata` component as a [hotspot=react-fragment file=1]`React Fragment` to create a reusable element that encompasses your whole web application. 

The entry point of your application is the [hotspot file=2]`index.js` file, and it's where your code is always going to be run. The performance benefit in using ReactJS is evident through the Virtual DOM that it offers, which is essentially a copy of the browser DOM that resides in memory. The Virtual DOM improves the performance of your web application as it plays a crucial role in the rendering process. The `react-dom` package provides DOM-specific methods that can be used in your application to get outside of the React model, if necessary. See, https://reactjs.org/docs/react-dom.html[ReactDOM^] to learn more about the Virtual DOM. 

To render the element that was made onto your webpage, invoke the [hotspot=dom-render file=2]`render` method provided by the DOM. Here, we rendered the `App` element on a DOM node.

Also, because you are requesting data from a different domain, you need to incorporate 
Enabling Cross-Origin Resource Sharing (CORS). Open liberty has a built-in configuration 
for CORS that can be added to the `server.xml`
See https://openliberty.io/guides/cors.html[Enabling Cross-Origin Resource Sharing (CORS)^] to learn more about CORS.

[role="code_command hotspot file=3", subs="quotes"]
----
#Update the `server.xml` file.#
`src/main/liberty/config/server.xml`
----
[role="edit_command_text"]
Add the [hotspot=cors file=3]`CORS` configuration.

Note: all the other dependencies that are installed in the project will show up in the `package.json`.

// =================================================================================================
// Importing the HTTP client
// =================================================================================================

== Importing the HTTP client

Your application needs a way to communicate with RESTful web services to retrieve their
resources. In this guide, you will use the axios Library that provides a lightweight HTTP client that will be used to make HTTP requests to external resources. https://github.com/axios/axios[axios^] is a promise-based HTTP client that allows you to send asynchronous requests to REST endpoints. Unlike frameworks such as Angular that have a built-in HTTP client, we need to use a third-party vendor HTTP client to render data from an API endpoint. 

To see an example of the Angular framework leveraging its HTTP client while running on the Open Liberty server, see: https://openliberty.io/guides/rest-client-angular.html[Consuming a RESTful web service with Angular^]. To learn more about the axios Library and its HTTP client, see: https://www.npmjs.com/package/axios[axios^].

Begin by importing the [hotspot=axios-library]`axios` Library into the `Fetchdata` Component.

Fetchdata.js
[source, javascript, linenums, role='code_column hide_tags=react-table,mount-posts,render-posts']
----
include::finish/src/main/frontend/src/Components/Fetchdata.js[]
----

The [hotspot=get-posts]`getPosts()` is the function that will utilize the axios API.

[role="code_command hotspot", subs="quotes"]
----
#Update the `Fetchdata.js` file.#
`src/main/frontend/src/Components/Fetchdata.js`
----
[role="edit_command_text"]
Add the [hotspot=get-posts]`getPosts()` function into the Fetchdata Component. 
Import the [hotspot=axios]`axios` HTTP call to read the artist JSON
containing the data from the sample JSON files. Then, you can
change the loading state by using the [hotspot=then-method]`.then()` method 
to display the data. On successfully getting a response, the state of 
the system changes by assigning [hotspot=data]`response.data` to [hotspot=data]`posts`.
Lastly, import the [hotspot=error-handling]`error` statement.

Since axios is promise-based, you can still use the [hotspot=error-handling]`.catch()` method that is used for 
error handling in promise composition. A benefit of axios is that it will reject the request promise 
if a `4xx` or `5xx` series error is returned.

// =================================================================================================
// Displaying the returned data 
// =================================================================================================

== Displaying the returned data

The [hotspot=mount-posts]`componentDidMount()` lifecycle method runs after the component output has been rendered to the DOM. Pagination can be used as a method used for handling data sets in React. In your application, you will render the columns in the paginated table, and define the [hotspot=header-id hotspot=header-name hotspot=header-followers hotspot=header-genres]`Header`
and [hotspot=accessor-id hotspot=accessor-name hotspot=accessor-followers hotspot=accessor-genres]`accessor` of each column.

Your paginated table is returned as `<React.Fragment>`, where you will define the props for the paginated [hotspot=table]`table`. The prop [hotspot=posts]`{posts}` corresponds to the consumed data from the API endpoint and is assigned to the `data` of the table. The prop [hotspot=columns]`{column}` corresponds to the rendered column object and is assigned to the `columns` of the table.

Fetchdata.js
[source, javascript, linenums, role='code_column']
----
include::finish/src/main/frontend/src/Components/Fetchdata.js[]
----

[role="code_command hotspot", subs="quotes"]
----
#Update the `Fetchdata.js` file.#
`src/main/frontend/src/Components/Fetchdata.js`
----
[role="edit_command_text"]
Import the [hotspot=react-table]`react table` libraries needed for the paginated table. Add the 
[hotspot=return-table]`return` statement to add the paginated table to your application.

Your application is available on http://localhost:3000[http://localhost:3000^].

// =================================================================================================
// Testing the React client
// =================================================================================================

== Testing the React client

No explicit code directly uses the consumed artist JSON, so you don’t need to write any test cases.

Whenever you change and build your React implementation, the application root at http://localhost:3000 reflects the changes automatically. You can visit the root to manually check whether the artist JSON was consumed correctly. You can rebuild only your React frontend by running the following command:

[role='command']
```
mvn generate-resources
```

When you are done checking the application root, exit development mode by pressing CTRL+C in the shell session where you ran the server, or by typing q and then pressing the enter/return key.

Although the React application in this guide is simple, when you build more complex React applications, testing becomes a crucial part of your development lifecycle. If you need to write test cases, follow the official unit testing and end-to-end testing documentation on the official https://reactjs.org/docs/testing.html[React^] page.

== Great work! You're done!

You have just accessed a simple RESTful web service and consumed its resources by using ReactJS in
Open Liberty.

include::{common-includes}/attribution.adoc[subs="attributes"]



